[workspace]
resolver = "2"
members = ["vos", "vos-ast", "vos-parser", "vos-generator", "vos-inspect"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Yggdrasill Team <192607617@qq.com>"]
license = "MPL-2.0"

[workspace.dependencies]
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dejavu = { git = "https://github.com/doki-land/dejavu-engine.git", branch = "dev" }
uuid = { version = "1", features = ["v7", "rng-getrandom"] }
getrandom = { version = "0.3", features = ["js"] }
vos-ast = { path = "vos-ast" }
vos-parser = { path = "vos-parser" }
vos-generator = { path = "vos-generator" }
vos-inspect = { path = "vos-inspect" }
