#[test]
fn prefers_aot_by_default() {
    assert!(vos_generator::prefers_aot());
}

#[test]
fn rust_header_via_dejavu() {
    let out = vos_generator::rust_file_header("rust").expect("header");
    assert!(out.contains("Generated by VOS"));
    assert!(out.contains("rust"));
}

#[test]
fn rust_struct_via_dejavu() {
    let out = vos_generator::rust_struct(
        "User",
        Some("A user row."),
        &[("id", "uuid::Uuid"), ("name", "String")],
    )
    .expect("struct");
    assert!(out.contains("pub struct User"));
    assert!(out.contains("pub id: uuid::Uuid"));
    assert!(out.contains("pub name: String"));
    assert!(out.contains("A user row."));
}

#[test]
fn module_with_struct() {
    use vos_generator::rust::RustField;
    let out = vos_generator::rust::module_with_struct(
        "persistence",
        "Session",
        None,
        &[RustField {
            name: "token".into(),
            ty: "String".into(),
        }],
    )
    .expect("module");
    assert!(out.contains("target: persistence"));
    assert!(out.contains("pub struct Session"));
}
