[package]
name = "vos"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Virtual Object Schema (VOS) language facade"
readme = "readme.md"

[dependencies]
vos-ast = { workspace = true }
vos-parser = { workspace = true }
vos-generator = { workspace = true }
vos-inspect = { workspace = true }
uuid = { workspace = true }
